{{- if .Values.jobmanager.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jobmanager.serviceAccount" . }}
  labels:
{{ include "flink.labels" . | indent 4 }}
  annotations:
{{ .Values.jobmanager.serviceAccount.annotations | toYaml | indent 4 }}
{{- end }}
---

{{- if .Values.taskmanager.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "taskmanager.serviceAccount" . }}
  labels:
{{ include "flink.labels" . | indent 4 }}
  annotations:
{{ .Values.jobmanager.serviceAccount.annotations | toYaml | indent 4 }}
{{- end }}
