apiVersion: v2
name: flink
description: Chart for Apache Flink

type: application

appVersion: "1.11.1"
version: 0.2.0

maintainers:
  - name: charts-maintainers
    email: charts-maintainers@riskfocus.com
home: https://github.com/riskfocus/helm-charts-public


dependencies:
  - name: zookeeper
    version: "2.1.*"
    repository: https://kubernetes-charts-incubator.storage.googleapis.com
    condition: zookeeper.enabled

